server:
  port: 8081
spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 18000000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz90ph1y3xc09g2h1io.mysql.rds.aliyuncs.com:3306/mpss?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true
    username: slb_mpss_dev
    password: 1234!@#$

mybatis:
  mapper-locations: classpath:mapper/*.xml