package rules
import com.slb.droolsdemo.entity.Student
import com.slb.droolsdemo.entity.Order
rule "student1 < 10岁"
    //no-loop true
    when
       $s : Student(age > 10) or $o : Order(realPrice == 100)
    then
//        Student student = new Student();
//        student.setAge(15);
//        $s.setAge(15);
//        insert(student);
        System.out.println("order岁规则出发");
end

rule "student1>10岁"
    when
      $s : Student(age < 20);
    then
        System.out.println($s.getAge());
        System.out.println("25岁规则出发");
end

query "query_1"(Student student)
      $s :  Student(age == student.age)
end

